// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SlojPodataka.TehnoloskeKlase;

#nullable disable

namespace SlojPodataka.Migrations
{
    [DbContext(typeof(TurnirDbContext))]
    [Migration("20260331142928_CelaMigracija")]
    partial class CelaMigracija
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SlojPodataka.KlasePodataka.Klub", b =>
                {
                    b.Property<int>("KlubID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KlubID"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BrojIgraca")
                        .HasColumnType("int");

                    b.Property<int>("BrojOsvojenihTitula")
                        .HasColumnType("int");

                    b.Property<int>("GodinaOsnivanja")
                        .HasColumnType("int");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazivKluba")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stadion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KlubID");

                    b.ToTable("Klub");
                });

            modelBuilder.Entity("SlojPodataka.KlasePodataka.Korisnik", b =>
                {
                    b.Property<int>("KorisnikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KorisnikID");

                    b.ToTable("Korisnik");
                });

            modelBuilder.Entity("SlojPodataka.KlasePodataka.StavkaZapisnika", b =>
                {
                    b.Property<int>("StavkaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StavkaID"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImeStrelca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KlubID")
                        .HasColumnType("int");

                    b.Property<int>("MinutGola")
                        .HasColumnType("int");

                    b.Property<int>("ZapisnikID")
                        .HasColumnType("int");

                    b.HasKey("StavkaID");

                    b.HasIndex("KlubID");

                    b.HasIndex("ZapisnikID");

                    b.ToTable("StavkaZapisnika");
                });

            modelBuilder.Entity("SlojPodataka.KlasePodataka.Zapisnik", b =>
                {
                    b.Property<int>("ZapisnikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZapisnikID"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumUtakmice")
                        .HasColumnType("datetime2");

                    b.Property<int>("DomacinID")
                        .HasColumnType("int");

                    b.Property<int>("GostID")
                        .HasColumnType("int");

                    b.Property<int>("KonacanRezultatDomacin")
                        .HasColumnType("int");

                    b.Property<int>("KonacanRezultatGost")
                        .HasColumnType("int");

                    b.Property<string>("TerenAdresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerenMesto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerenNaziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZapisnikID");

                    b.HasIndex("DomacinID");

                    b.HasIndex("GostID");

                    b.ToTable("Zapisnik");
                });

            modelBuilder.Entity("SlojPodataka.KlasePodataka.StavkaZapisnika", b =>
                {
                    b.HasOne("SlojPodataka.KlasePodataka.Klub", "Klub")
                        .WithMany("Golovi")
                        .HasForeignKey("KlubID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SlojPodataka.KlasePodataka.Zapisnik", "Zapisnik")
                        .WithMany("Stavke")
                        .HasForeignKey("ZapisnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klub");

                    b.Navigation("Zapisnik");
                });

            modelBuilder.Entity("SlojPodataka.KlasePodataka.Zapisnik", b =>
                {
                    b.HasOne("SlojPodataka.KlasePodataka.Klub", "Domacin")
                        .WithMany("DomacinUtakmice")
                        .HasForeignKey("DomacinID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SlojPodataka.KlasePodataka.Klub", "Gost")
                        .WithMany("GostUtakmice")
                        .HasForeignKey("GostID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Domacin");

                    b.Navigation("Gost");
                });

            modelBuilder.Entity("SlojPodataka.KlasePodataka.Klub", b =>
                {
                    b.Navigation("DomacinUtakmice");

                    b.Navigation("Golovi");

                    b.Navigation("GostUtakmice");
                });

            modelBuilder.Entity("SlojPodataka.KlasePodataka.Zapisnik", b =>
                {
                    b.Navigation("Stavke");
                });
#pragma warning restore 612, 618
        }
    }
}
